name: Docker Build and Push
on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t deepakdocker25/docker-client-app:${{ github.ref }} .
      
    - name: Push Docker image to Docker Hub
      run: docker push deepakdocker25/docker-client-app:${{ github.ref }}
